# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
install coreutils
# Install some other useful utilities like `sponge`
install moreutils

# Install latest Zsh
install zsh

# Install wget with IRI support
install wget --enable-iri

# Install more recent versions of some OS X tools
install vim --override-system-vi
install homebrew/dupes/grep
#install josegonzalez/homebrew-php/php55

# Install other useful binaries
install ack
install autoconf
install direnv
install git
install git-flow
install hub
install mobile-shell
install openssl
install p7zip
install pv
install readline
install tig
install tmux
install tree
install webkit2png
install z

tap homebrew/binary
# install docker
# install boot2docker
install packer

tap homebrew/versions

# Remove outdated versions from the cellar
cleanup
