# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install latest Zsh
install zsh

# Install wget with IRI support
install wget --enable-iri

# Install more recent versions of some OS X tools
install vim --override-system-vi
tap homebrew/dupes
install homebrew/dupes/grep
tap josegonzalez/homebrew-php
#install php55

# Install other useful binaries
install coreutils
install ack
install autoconf
install git
install git-flow
install hub
install mobile-shell
install openssl
install readline
install tig
install tmux
install tree
install webkit2png

tap homebrew/binary
install docker
install boot2docker
install packer

tap homebrew/versions

# Remove outdated versions from the cellar
cleanup
